// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// code.cpp
list tg_scan_tokens_cpp(std::string src);
extern "C" SEXP _readtextgrid_tg_scan_tokens_cpp(SEXP src) {
  BEGIN_CPP11
    return cpp11::as_sexp(tg_scan_tokens_cpp(cpp11::as_cpp<cpp11::decay_t<std::string>>(src)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_readtextgrid_tg_scan_tokens_cpp", (DL_FUNC) &_readtextgrid_tg_scan_tokens_cpp, 1},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_readtextgrid(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
