# Generated by cpp11: do not edit by hand

cpp_tg_scan_tokens <- function(src) {
  .Call(`_readtextgrid_cpp_tg_scan_tokens`, src)
}

cpp_parse_praat_numbers <- function(x) {
  .Call(`_readtextgrid_cpp_parse_praat_numbers`, x)
}
